project:
  type: book
  output-dir: docs

book:
  title: "Socio-economic analysis with `Python`"
  author: "Thomas de Graaff"
  date: "10/07/2025"
  chapters:
    - index.qmd
    - intro.qmd
    #- linear_regression.qmd
    #- multivariate.qmd
    #- assessment.qmd
    #- conclusion.qmd
    - references.qmd
  appendices:
     - appendix.qmd

bibliography: references.bib

format:
  html:
    fontsize: 1.0em
    include-in-header:
      - text: |
          <script>
          window.MathJax = {
            tex: {
              tags: 'ams'
            }
          };
          </script>
    theme: cosmo
    toc-depth: 4

  pdf:
    documentclass: scrreprt



